import sys, time

topic=input().strip(); participants=input().strip(); duration=input().strip()
print('🏢 AI MEETING vMOCK', flush=True)
print('⏱️ 03:00.000 | 발언 #1', flush=True)
print('', flush=True); print('💬 CEO', flush=True); print('사진은 크게 갑니다.', flush=True); print('[assert_position / firm]', flush=True)
time.sleep(.05)
print('⏱️ 02:50.000 | 발언 #2', flush=True)
print('', flush=True); print('💬 디자이너', flush=True); print('그렇게 크게는 못 받습니다.', flush=True); print('[challenge / annoyed]', flush=True)
print('📝 서기: 벌써 의견이 갈립니다.', flush=True)
time.sleep(.05)
print('⏱️ 02:40.000 | 발언 #3', flush=True)
print('', flush=True); print('💬 CEO', flush=True); print('그럼 회사 메시지가 먼저 보이게 제한하죠.', flush=True); print('[decide / firm]', flush=True)
print('회의가 종료되었습니다.', flush=True)
print('📍 결정 상태', flush=True); print('✅ 결정 완료', flush=True); print('결정 방식: 👔 결정권자 결정', flush=True)
print('📊 발언 횟수', flush=True); print('CEO: 2회', flush=True); print('디자이너: 1회', flush=True); print('총 유효 발언: 3회', flush=True); print('종료 이유: leader_decision', flush=True)
print('📌 최종 결정', flush=True); print('- 대표 사진은 넣되 회사 메시지가 먼저 보이게 제한한다.', flush=True)
print('💡 미확정 제안', flush=True); print('- 없음', flush=True)
print('✅ 후속 작업', flush=True); print('- 없음', flush=True)
print('❔ 현재 필요한 미확인 정보', flush=True); print('- 없음', flush=True)
print('❓ 남은 핵심 쟁점', flush=True); print('- 없음', flush=True)
